### PR TITLE
Release 0.1.0

### PR DESCRIPTION
**Pull request by fairlighteth**

### CODE REVIEW

**Comment by elena-zh** [comment]
Hey @fairlighteth , nice app!!
Some issues I have found: 
1. Cow bottle pick looks a bit strange in a tablet view (maybe we need to fill in the entire area with blue or add some kind of a boarder between the image and the footer?)
no boarder - tablet
2. Tablet/Mobile view: footer elements become invisible when hover a mouse on them
hover effect
3. Overview: Cow icon looks like an outdated on the pic 
cow icon
4. Overview: It would be also nice to update images with CoW DAO (instead of CowDAO)
cow dao
5. Overview: It would be great to add an anchor link to the  ‘How to apply’ for the quick navigation
add anchor
6. Overview: There is a section that has a different formatting on the FAQ: 
different sections FAQ
7. Overview: there are some places with not correct spelling of CoW:
cow
cow1
8. Overview: missing periods in the end of sentences: 
period 3
Period 5
period
Periods 4
preiods 2

9. Terms: is COW spelling correct here?
is it ok COW
10. Terms: missing period: 
period terms1
11. Terms: a lot of line breaks where they are not needed: 
TC line break
TC line break2
TC line break3
TC line break4
TC line break5
TC line break6
TC line break7
TC line break8
TC lline break0

**Comment by elena-zh** [comment]
As far as I can understand, we use a 3rd party component for a grant application. 
I have done a quick test of it and will highlight the most critical issues I found: 
1. When I submit a request, a successful message appears in the middle of the form and a user needs to scroll the page to see it somehow https://watch.screencastify.com/v/QywFzuVhenBxWzyHd4k4 . Can we make the section smaller and auto-scroll  a user to top once the form is submitted?
2. Report form elements exceed the form width
report a malicious form
3. Some elements also truncated in mobile view 
image
4. This is how the grants tracker is displayed on the page (see a lot of truncated elements)
how look like
Ui elements
image

5. Filter options are not displayed in iOS
image

6. Link navigate to the 404 page (may be will be fixed after the release)
image
image



Anyways, let me know please if I need to test this form more thoroughly (might take more than 1 day to run all cases related to the grant creation and tracker overview). 

Thanks!

**Comment by fairlighteth** [comment]
@elena-zh I've addressed most of your comments, with the exception of point 3 and 4 (editing the images).

I also changed the Airtable integration by **not embedding the forms** anymore, but rather link to the form on the external Airtable page.

**Comment by elena-zh** [comment]
Hey @fairlighteth , great job!
Decision to add links to the form on the external Airtable page is awesome!
Anyways, I still can find issues on the external page, so still my question is whether I need to test this form thoroughly and report all of them, or it is not mine zone of responsibility. 

**And here are a few issues and proposals from my side related to our app:** 
1. Overview and Terms: I think, it would be nice to add a link to tokens that will navigate to a blockexplorer, WDYT?
token links
2. Overview: It would be also great to add an anchor link that will navigate a user to the described section
anchor link
3.  Still there are some missing periods in the Overview page: 
over-period
over-period1
over-period2
4. (not sure of it is an issue) Footer position is different on Overview and Apply/Tracker pages. Shouldn't it be the same (at the bottom of the page)?
bott
not bottom
5. (not sure of it is an issue): when scroll down the Home page, menu hides the app logo (it looks like transparent). Can we change it to the dark-blue one?
change color

**Comment by fairlighteth** [comment]
@elena-zh Appreciate you reviewing this thoroughly again.

> ...or it is not mine zone of responsibility.

Yes, I'd say that's out of scope for us now.

As for point 3, I've decided to remove all points, given these are list items.

Otherwise, I've addressed all your other points now. Please review!

**Comment by elena-zh** [comment]
Hey @fairlighteth , thanks for the fixes!
I'm approving the PR, but again will list some my new nitpicks: 
1. Would it be possible to add links to tokens here as well (Overview page)? 
links
2. Terms page: there is 'xdai' in the text. But I see 'wxDAI' in the Overview page, so maybe it needs to be changed? Besides, it would be also awesome to add links there
Screenshot_5
3. Terms: space is missing: 
space

**Review by elena-zh — APPROVED** [review]

**Comment by elena-zh** [comment]
Btw, @fairlighteth , the page turns to be completely pink/peach colored at the bottom in a mobile view in a real device. Is this OK? 

image

**Comment by fairlighteth** [comment]
@elena-zh addressed all 3 points now.

As for the iOS gradient: This seems to be iOS specific unfortunately, where it doesn't respect `background-position: fixed`.

**Comment by fairlighteth** [comment]
@elena-zh The first image has been updated as well (uses the new logos).

**Comment by elena-zh** [comment]
Looks good to me, thank you!

**Comment by fairlighteth** [comment]
@elena-zh Great 👍🏼 Thank you again for the review.

**Pull request merged**
